name: Go

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Get dependencies
      run: |
        GO111MODULE=off go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build
      run: GO111MODULE=off CGO_ENABLED=0 go build -v ./...
      
    - name: Build windows
      run: GO111MODULE=off CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o windows -v ./...
    
    - name: Build arm
      run: GO111MODULE=off CGO_ENABLED=0 GOARCH=arm GOARM=5 go build -o arm -v ./...
      
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with: 
        branch: gh-pages
        folder: .
